"""initial_schema

Revision ID: 16603561148e
Revises: 
Create Date: 2026-04-23 19:53:29.745481+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16603561148e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUALIFYING', 'QUALIFIED', 'SCHEDULED', 'INTERVENTION', 'DISQUALIFIED', 'CLOSED', name='lead_status'), nullable=False),
    sa.Column('segment', sa.String(length=255), nullable=True, comment='Segmento de atuação da empresa do lead'),
    sa.Column('budget', sa.String(length=255), nullable=True, comment='Orçamento estimado para implementação'),
    sa.Column('timeline', sa.String(length=255), nullable=True, comment='Prazo estimado para implementação'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_phone_number'), 'leads', ['phone_number'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True, comment='ID do evento no Google Calendar'),
    sa.Column('meeting_url', sa.String(length=500), nullable=True, comment='Link do Google Meet ou outra plataforma'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_table('conversations',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_AGENT', 'TAKEN_OVER', 'COMPLETED', 'ABANDONED', name='conversation_status'), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('agent_state_snapshot', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True, comment='Email/ID do consultor que assumiu a conversa'),
    sa.Column('intervention_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp da primeira mensagem do lead (início do SLA)'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Quando o agendamento foi concluído (fim do SLA)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_number'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
